252 loadcontract
AplaProject/go-apla pull request #112
Opened 2018-01-12 03:48 UTC by gentee

Moved loading contracts before daemons

2018-01-12 15:34 UTC, ghost requested changes

2018-01-12 15:34 UTC, dvork1ng commented on packages/daylight/daemonsctl/daemonsctl.go
> +	log.Info("load contracts")
can you use here logrus?

2018-01-12 15:34 UTC, dvork1ng commented on packages/daylight/daemonsctl/daemonsctl.go
> +	log.Info("start daemons")
and here

2018-01-13 09:18 UTC, gentee commented on packages/daylight/daemonsctl/daemonsctl.go
> +	log.Info("load contracts")
Changed log to logrus

2018-01-15 11:08 UTC, ghost approved these changes

2018-01-17 10:42 UTC, merged