297 roles
AplaProject/go-apla pull request #118
Opened 2018-01-15 13:37 UTC by gentee

Checked role tables

2018-01-15 14:18 UTC, ghost approved these changes

2018-01-15 14:37 UTC, ghost approved these changes

2018-01-18 06:51 UTC, ghost approved these changes

2018-01-19 18:03 UTC, potehinre requested changes

2018-01-19 18:03 UTC, potehinre commented on packages/migration/ecosysystem.go
> +			"rb_id" bigint NOT NULL DEFAULT '0'
rb_id is obsolete

2018-01-19 18:03 UTC, potehinre commented on packages/migration/ecosysystem.go
> +			"rb_id" bigint NOT NULL DEFAULT '0'
rb_id is obsolete

2018-01-19 18:03 UTC, potehinre commented on packages/migration/ecosysystem.go
> +			"rb_id" bigint NOT NULL DEFAULT '0'
rb_id is obsolete

2018-01-20 10:16 UTC, gentee commented on packages/migration/ecosysystem.go
> +			"rb_id" bigint NOT NULL DEFAULT '0'
Removed all rb_id

2018-01-22 05:34 UTC, potehinre approved these changes

2018-01-22 06:04 UTC, merged