add func TokenTransferWithHistory
AplaProject/go-apla pull request #160
Opened 2018-02-06 08:05 UTC by rpoletaev

add model history
add monitoring funcs
add limit check to block_generator

2018-02-06 10:22 UTC, potehinre approved these changes

2018-02-06 10:22 UTC, potehinre commented on packages/model/history.go
> +	db := GetDB(nil)
better pass transaction as first parameter for that function, and then GetDB(transaction)

2018-02-06 10:22 UTC, potehinre commented on packages/model/history.go
> +	db := GetDB(nil)
Same stuff

2018-02-06 10:22 UTC, potehinre commented on packages/model/history.go
> +	db := GetDB(nil)
same stuff

2018-02-06 10:22 UTC, potehinre commented on packages/notificator/token_movements.go
> +		log.WithFields(log.Fields{"error": err}).Error("check common token movement")
type: consts.DBError

2018-02-06 10:22 UTC, potehinre commented on packages/notificator/token_movements.go
> +		log.WithFields(log.Fields{"error": err}).Error("check from to token movement")
same stuff

2018-02-06 10:22 UTC, potehinre commented on packages/notificator/token_movements.go
> +		log.WithFields(log.Fields{"error": err}).Error("check token movement per block")
Same stuff

2018-02-07 05:55 UTC, ghost requested changes

2018-02-07 05:55 UTC, dvork1ng commented on packages/model/history.go
> +	tokenMovementQtyPerBlockLimit = 100
common consts should be moved to consts package

2018-02-07 05:55 UTC, dvork1ng commented on packages/notificator/token_movements.go
> +	networkPerDayLimit            = 100000000
common consts should be moved to consts package

2018-02-07 19:48 UTC, potehinre approved these changes

2018-02-08 06:50 UTC, ghost approved these changes

2018-02-21 09:58 UTC, merged