420 role support
AplaProject/go-apla pull request #178
Opened 2018-02-12 12:55 UTC by rpoletaev

2018-02-13 04:19 UTC, potehinre requested changes

2018-02-13 06:22 UTC, ghost approved these changes

2018-02-13 07:06 UTC, potehinre approved these changes

2018-03-14 04:09 UTC, Saurer requested changes
Implementation is missing role_id param in the API endpoint. Consider adding ?role_id:int64 to packages/api/route.go:75

2018-03-16 10:02 UTC, Saurer approved these changes

2018-03-20 07:57 UTC, ghost approved these changes

2018-03-29 11:41 UTC, merged