446 add vde mode support
AplaProject/go-apla pull request #188
Opened 2018-02-15 10:52 UTC by rpoletaev

2018-02-15 15:18 UTC, dvork1ng commented on packages/api/route.go
> +	if !*conf.IsVDEMode {
why ecosystemparam route is allowed in VDE mode? The same thing about systemparams route

2018-02-15 15:18 UTC, dvork1ng commented on packages/smart/funcs.go
> +	if sc.VDE && *conf.IsVDEMode {
what does it mean "if VDE && IsVDE"?

2018-02-15 15:18 UTC, dvork1ng commented on packages/template/funcs.go
> +	if sc.VDE && *conf.IsVDEMode {
the same as above

2018-02-16 11:46 UTC, potehinre approved these changes

2018-02-20 16:24 UTC, ghost requested changes

2018-02-20 16:24 UTC, dvork1ng commented on packages/api/route.go
> +	if !*conf.IsVDEMode {
be more attentive please. Should it work in vde mode?
get(`ecosystems`, ``, authWallet, ecosystems)

2018-02-22 06:21 UTC, ghost approved these changes

2018-03-14 12:12 UTC, closed without merging