475-amount bugfix
AplaProject/go-apla pull request #194
Opened 2018-02-19 15:17 UTC by gentee

Fixed updating block data

2018-02-20 16:25 UTC, ghost requested changes

2018-02-20 16:25 UTC, dvork1ng commented on packages/parser/common_parse_data_full.go
> +		b.BinData = nbb
what is nbb?

2018-02-21 04:34 UTC, potehinre approved these changes

2018-02-21 07:45 UTC, gentee commented on packages/parser/common_parse_data_full.go
> +		b.BinData = nbb
Renamed to newBlockData

2018-02-21 07:46 UTC, ghost approved these changes

2018-02-23 10:11 UTC, merged