Added multipart file uploading
AplaProject/go-apla pull request #212
Opened 2018-03-01 07:58 UTC by gentee

2018-03-02 05:25 UTC, potehinre requested changes

2018-03-02 05:25 UTC, potehinre commented on packages/api/contract.go
> +							log.WithFields(log.Fields{"type": consts.InvalidObject, "error": err}).Error("reading multipart file")
type: consts.IOError

2018-03-02 05:25 UTC, potehinre commented on packages/api/data.go
> +			w.Header().Set("Cache-Control", "public,max-age=604800,immutable")
move max_age to consts

2018-03-02 05:25 UTC, potehinre commented on packages/api/prepare.go
> +						log.WithFields(log.Fields{"type": consts.InvalidObject, "error": err}).Error("getting multipart file")
type: consts.IOError

2018-03-02 05:25 UTC, potehinre commented on packages/api/prepare.go
> +						log.WithFields(log.Fields{"type": consts.InvalidObject, "error": err}).Error("reading multipart file")
type: consts.IOError

2018-03-02 05:25 UTC, potehinre commented on packages/parser/common_parse_data_full.go
> +	getHash := func(input []byte) (string, error) {
Code duplication, move that func to utils

2018-03-02 07:27 UTC, gentee commented on packages/api/api.go
> +			r.ParseMultipartForm(15 * 1024 * 1024)
Fixed all review comments

2018-03-07 05:51 UTC, potehinre approved these changes

2018-03-07 07:53 UTC, ghost approved these changes

2018-06-07 21:16 UTC, closed without merging