feature/523 editnew
AplaProject/go-apla pull request #224
Opened 2018-03-13 09:43 UTC by gentee

2018-03-13 17:56 UTC, ghost requested changes

2018-03-13 17:56 UTC, dvork1ng commented on packages/smart/smart_p.go
> +	if !accessContracts(sc, "ActivateContract", "DeactivateContract") {
strings have to be moved to constants

2018-03-13 17:56 UTC, dvork1ng commented on packages/smart/smart_p.go
> +	if !accessContracts(sc, "ActivateContract", "DeactivateContract") {
the same

2018-03-13 17:56 UTC, dvork1ng commented on packages/smart/smart_p.go
> +	if !accessContracts(sc, "NewContract", "Import") {
one more plain strings

2018-03-14 13:26 UTC, gentee commented on packages/smart/smart_p.go
> +	if !accessContracts(sc, "ActivateContract", "DeactivateContract") {
Fixed, contract names moved to const.

2018-03-15 03:44 UTC, merged