554 network stopping
AplaProject/go-apla pull request #254
Opened 2018-03-27 11:58 UTC by dchertkov

2018-03-27 12:59 UTC, potehinre requested changes

2018-03-27 12:59 UTC, potehinre commented on packages/daylight/start.go
> +		//go func() {
Commented code prohibited

2018-03-27 12:59 UTC, potehinre commented on cmd/stopNetwork.go
> +				log.WithError(err).Errorf("Sending request to %s", addr)
better use WithFields, than formatted logging

2018-03-27 12:59 UTC, potehinre commented on cmd/stopNetwork.go
> +		log.Infof("Successful: %d, failed: %d", len(addrsForStopping)-errCount, errCount)
the same

2018-03-27 12:59 UTC, potehinre commented on cmd/stopNetwork.go
> +			log.Infof("Sending request to %s", addr)
the same

2018-03-27 12:59 UTC, potehinre commented on packages/tcpserver/type3.go
> +		log.WithError(err).Error("parsing cert")
Here and below logging: error types? ParseError, InvalidObjectError

2018-03-27 12:59 UTC, potehinre commented on packages/tcpserver/type3.go
> +		log.WithError(err).Error("binary marshaling")
MarshallingError

2018-03-27 12:59 UTC, potehinre commented on packages/tcpserver/type3.go
> +		log.WithError(err).Error("hashing data")
CryptoError

2018-03-27 12:59 UTC, potehinre commented on packages/tcpserver/type3.go
> +		log.WithError(err).Error("inserting tx to database")
DBError

2018-03-29 06:49 UTC, ghost requested changes

2018-03-29 06:49 UTC, dvork1ng commented on cmd/stopNetwork.go
> +const reqType = 3
what does it mean? Add a comment or give more semantic name.

2018-03-29 09:22 UTC, potehinre approved these changes

2018-04-02 15:47 UTC, ghost approved these changes

2018-04-09 15:20 UTC, potehinre approved these changes

2018-04-17 12:58 UTC, merged