409 console setup
AplaProject/go-apla pull request #28
Opened 2017-11-22 14:29 UTC by maxp

2017-11-22 20:08 UTC, potehinre approved these changes

2017-11-23 07:36 UTC, potehinre commented
Ток чтото оно не билдится ни в трэвисе, ни в TC

2017-12-01 09:19 UTC, potehinre requested changes
This will be done after config refactoring

2017-12-07 17:14 UTC, ghost requested changes

2017-12-07 17:14 UTC, dvork1ng commented on packages/api/install.go
> +
create a task & remove this comment

2017-12-07 17:14 UTC, dvork1ng commented on packages/api/install.go
> +	//
why config.ini?
is this sample actual?

2018-01-28 02:44 UTC, closed without merging