Added functions for AWS by Aleksey63
AplaProject/go-apla pull request #41
Opened 2017-11-29 05:55 UTC by gentee

2017-12-01 08:30 UTC, potehinre approved these changes

2017-12-07 16:38 UTC, ghost requested changes

2017-12-07 16:38 UTC, dvork1ng commented on packages/api/vde_test.go
> +	var lret contentResult
please, use semantic names

2017-12-07 16:38 UTC, dvork1ng commented on packages/smart/funcs.go
> +func GetMapKeys(in map[string]interface{}) []interface{} {
useless comment

2017-12-07 16:38 UTC, dvork1ng commented on packages/smart/funcs.go
> +	i, sorted := 0, make([]string, len(m))
useless comment

2017-12-07 16:38 UTC, dvork1ng commented on packages/smart/smart.go
> +	var name string
useless comment

2017-12-07 16:38 UTC, dvork1ng commented on packages/smart/funcs.go
> +
useless comment

2017-12-11 09:17 UTC, gentee commented on packages/api/vde_test.go
> +	var lret contentResult
It has been renamed to retContent.

2017-12-11 09:34 UTC, ghost approved these changes

2017-12-11 11:55 UTC, merged