Added VDE Import and Lang contracts
AplaProject/go-apla pull request #42
Opened 2017-11-29 06:17 UTC by gentee

2017-12-01 08:28 UTC, potehinre approved these changes

2017-12-07 15:53 UTC, ghost requested changes

2017-12-07 15:53 UTC, dvork1ng commented on packages/api/vde_test.go
> +	var lret contentResult
let's use more semantic variable name.

2017-12-07 15:53 UTC, dvork1ng commented on packages/smart/smart.go
> +	var name string
Useless comment

2017-12-07 15:53 UTC, dvork1ng commented on packages/smart/smart_p.go
> +	ret, _ := language.LangText(idRes, int(sc.TxSmart.EcosystemID), lang, sc.VDE)
useless comment

2017-12-07 15:53 UTC, dvork1ng commented on packages/smart/smart_p.go
> +	language.UpdateLang(int(sc.TxSmart.EcosystemID), name, trans, sc.VDE)
useless comment

2017-12-11 10:04 UTC, ghost approved these changes

2017-12-12 05:54 UTC, merged