Concurrent map writing error fixed
AplaProject/go-apla pull request #45
Opened 2017-11-29 08:50 UTC by yddmat

2017-11-29 08:56 UTC, potehinre requested changes

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +	sync.Mutex
Maybe RWLock would be better, it provides better concurrency on read

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +				notifications.Lock()
I think, it would be better to move this as a Set method to ConcurrentNotifications structure

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +			if *notifications.storage[ecosystemID].lastNotifID < id {
It should be Get method on ConcurrentNotifications structure

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +	if _, ok := notifications.storage[EcosystemID(ecosystemID)]; !ok {
notifications.Get

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +		notifications.Lock()
notifications.Set

2017-11-29 08:56 UTC, potehinre commented on packages/notificator/notificator.go
> +	notifications.storage[EcosystemID(ecosystemID)].UserIDs[UserID(userID)] = 0
Set

2017-11-29 11:21 UTC, potehinre commented
Good, but it still fails :(. Maybe there is another concurrent map read/write error

2017-11-30 05:07 UTC, gentee submitted a review, later dismissed

2017-11-30 05:54 UTC, gentee reviewed
It is looks like it doesn't work correctly.

2017-12-01 07:52 UTC, potehinre approved these changes

2017-12-01 07:52 UTC, merged