27 Ignore commission for not existing keys
AplaProject/go-apla pull request #51
Opened 2017-12-01 11:18 UTC by gentee

2017-12-07 10:25 UTC, potehinre approved these changes

2017-12-07 15:35 UTC, ghost requested changes

2017-12-07 15:35 UTC, dvork1ng commented on packages/smart/selective.go
> +	table string, whereFields, whereValues []string, generalRollback bool, ifexist bool) (int64, string, error) {
may be "exists" instead of "ifexist"?

2017-12-11 13:53 UTC, ghost approved these changes

2017-12-11 13:54 UTC, merged