27 fixed rollback for NewEcosystem, NewTable & NewColumn
AplaProject/go-apla pull request #54
Opened 2017-12-05 03:39 UTC by gentee

2017-12-07 09:58 UTC, potehinre requested changes

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +	NotRollback   bool
Use of inverted logic, maybe it would be better to rename field to Rollback, and do && sc.Rollback, instead of && !sc.NotRollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +	qcost, lastID, err = sc.selectiveLoggingAndUpd(strings.Split(params, `,`), val, tblname, nil, nil, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +	qcost, _, err = sc.selectiveLoggingAndUpd(columns, val, tblname, []string{`id`}, []string{converter.Int64ToStr(id)}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +		getDefTableName(sc, `tables`), []string{`name`}, []string{name}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +		tables, []string{`name`}, []string{tableName}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/funcs.go
> +		tables, []string{`name`}, []string{tableName}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +	sc.NotRollback = true
sc.Rollback = false

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +	_, _, err = sc.selectiveLoggingAndUpd(fields, values, "system_parameters", []string{"name"}, []string{name}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +	qcost, _, err = sc.selectiveLoggingAndUpd(columns, val, tblname, []string{column}, []string{fmt.Sprint(value)}, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +	qcost, lastID, err = sc.selectiveLoggingAndUpd(strings.Split(params, `,`), val, tblname, nil,
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +		nil, !sc.VDE && !sc.NotRollback)
&& sc.Rollback

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +		// if there is not such hash then NewEcosystem was faulty. Do nothing.
log that ecosystem has not been found

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +		// if there is not such hash then NewTable was faulty. Do nothing.
logging?

2017-12-07 09:58 UTC, potehinre commented on packages/smart/smart_p.go
> +		// if there is not such hash then NewColumn was faulty. Do nothing.
logging?

2017-12-07 13:47 UTC, ghost requested changes

2017-12-07 13:47 UTC, dvork1ng commented on packages/model/rollback_tx.go
> +func (rt *RollbackTx) Get(dbTransaction *DbTransaction, transactionHash []byte, tableName string) (bool, error) {
useless comment

2017-12-07 13:47 UTC, dvork1ng commented on packages/model/tables.go
> +func (t *Table) IsExistsByPermissionsAndTableName(transaction *DbTransaction, columnName, tableName string) (bool, error) {
useless comment

2017-12-07 13:47 UTC, dvork1ng commented on packages/smart/funcs.go
> +	NotRollback   bool
useless comment

2017-12-12 05:38 UTC, potehinre approved these changes

2017-12-12 05:38 UTC, potehinre commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.NotFound}).Error("system states roollback")
roollback?

2017-12-12 05:38 UTC, potehinre commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.NotFound}).Error("table roollback")
roollback?

2017-12-12 05:38 UTC, potehinre commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.NotFound}).Error("column roollback")
roolback?

2017-12-12 06:38 UTC, ghost requested changes

2017-12-12 06:38 UTC, dvork1ng commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.NotFound}).Error("table rollback")
Wrong error message. Not table rollback, but record in this table.

2017-12-12 06:38 UTC, dvork1ng commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.DBError, "error": err}).Error("deleting rollback table")
Wrong error message. Deleting record in rollback table

2017-12-12 06:38 UTC, dvork1ng commented on packages/smart/smart_p.go
> +		log.WithFields(log.Fields{"type": consts.DBError, "error": err}).Error("getting rollback column")
Wrong message. Getting rollback record or getting column rollback?

2017-12-12 06:58 UTC, ghost approved these changes

2017-12-12 08:47 UTC, merged