hotfix/1249 pub
AplaProject/go-apla pull request #596
Opened 2018-11-09 09:20 UTC by gentee

Changed pubkey for RFC

2018-11-09 10:42 UTC, potehinre requested changes

2018-11-09 10:42 UTC, potehinre commented on packages/api/login.go
> +	if len(dataKey) == 65 && dataKey[0] == 4 {
move to separate function

2018-11-09 10:42 UTC, potehinre commented on packages/crypto/converter.go
> +	if len(pubKey) == 65 && pubKey[0] == 4 {
same stuff

2018-11-09 15:50 UTC, gentee commented on packages/crypto/converter.go
> +	if len(pubKey) == 65 && pubKey[0] == 4 {
Fixed.

2018-11-09 15:50 UTC, gentee commented on packages/api/login.go
> +	if len(dataKey) == 65 && dataKey[0] == 4 {
Fixed

2018-11-12 06:34 UTC, potehinre approved these changes

2018-11-12 08:40 UTC, merged