123 Refactored and moved GenerateFirstBlock function to install package
AplaProject/go-apla pull request #71
Opened 2017-12-15 07:37 UTC by dchertkov

2017-12-15 09:39 UTC, potehinre requested changes

2017-12-15 09:39 UTC, potehinre commented on packages/install/first_block.go
> +		return
need to log CryptoError

2017-12-15 09:39 UTC, potehinre commented on packages/install/first_block.go
> +	if len(*value) == 0 {
are you sure that value is not nil?

2017-12-15 09:39 UTC, potehinre commented on packages/install/first_block.go
> +		*value = pub
Anyway i think it would be better idea to make this function immutable, and return value, instead of modifying it in place

2017-12-15 09:39 UTC, potehinre commented on packages/api/install.go
> +	if install.IsNotExistFirstBlock() {
Use of inverted logic. I think !install.FirstBlockExists() would be better

2017-12-15 09:39 UTC, potehinre commented on packages/install/first_block.go
> +func IsNotExistFirstBlock() bool {
Inverted logic, need to rewriteit like FirstBlockExist

2017-12-15 10:42 UTC, potehinre requested changes

2017-12-15 10:42 UTC, potehinre commented on packages/install/first_block.go
> +func firstBlockPublicKey() ([]byte, error) {
Useless function

2017-12-15 10:42 UTC, potehinre commented on packages/install/first_block.go
> +func firstBlockNodePublicKey() ([]byte, error) {
Useless function

2017-12-15 10:42 UTC, potehinre commented on packages/install/first_block.go
> +	conf.Config.KeyID = address
Very silently modifies config

2017-12-15 10:46 UTC, potehinre requested changes

2017-12-15 10:46 UTC, potehinre commented on packages/install/first_block.go
> +func getPublicKeyAndCreateKeyPair(value *string, privFilename, pubFilename string) ([]byte, error) {
There should be no functions with "AND" in the name, because single function - single responsibility

2017-12-19 10:40 UTC, ghost requested changes

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +		return
should here be logging?

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +		return
should here be logging?

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +		return err
should here be logging?

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +			return err
should here be logging?

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +			return err
should here be logging?

2017-12-19 10:40 UTC, dvork1ng commented on packages/install/first_block.go
> +		return err
should here be logging?

2017-12-19 18:03 UTC, ghost approved these changes

2017-12-19 18:09 UTC, potehinre approved these changes

2018-01-11 06:19 UTC, merged